name: 'Google Cloud Deploy Actions Collection'
description: 'Run Cloud Deploy actions for Google Project'
author: 'drew.mercer'
inputs: 
  deploy_type:
    description: 'Cloud Run or GKE'
    required: true
  directory:
    description: 'Directory to run Cloud Deploy in'
    required: false
    default: './service'
  project_id: 
    description: 'Project ID'
    required: true
  environment: 
    description: 'Environment'
    required: false
  region: 
    description: 'Region'
    required: true
  service_name: 
    description: 'Service Name'
    required: true
  image: 
    description: 'Docker Image URI'
    required: true
  cloud_run_sa: 
    description: 'Cloud Run Service Account'
    required: true

runs:
  using: "composite"
  steps:
  - id: create_service
    if: ${{ inputs.deploy_type == 'cloudrun' }}
    run: |
      export SERVICE_NAME="${{ inputs.service_name }}"
      export PROJECT_ID="${{ inputs.project_id }}"
      export IMAGE="${{ inputs.image }}"
      export CLOUD_RUN_SA="${{ inputs.cloud_run_sa }}"
      export ENVIRONMENT="${{ inputs.environment }}"
      envsubst < ${{ inputs.directory}}/container.yaml > container-${{ inputs.environment }}.yaml
      cat container-${{ inputs.environment }}.yaml
    shell: bash

  - id: deploy_service
    if: ${{ inputs.deploy_type == 'cloudrun' }}
    uses: google-github-actions/deploy-cloudrun@v2
    with:
      service: ${{ env.service_name }}
      region: ${{ inputs.region }}
      metadata: container-${{ inputs.environment }}.yaml